[build-system]
requires = ['hatchling']
build-backend = 'hatchling.build'

[project]
name = 'instagram'
version = '2.0'
dependencies = ['django']

[project.optional-dependencies]
dev = ['pytest', 'Pillow']