# Generated by Django 4.2.1 on 2023-06-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
