# Generated by Django 4.2.1 on 2023-07-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_alter_post_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='/media/images/avatars/default.png', upload_to='./images/'),
        ),
    ]
